services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: aplicacion_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_container
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

volumes:
  mysql_data: